print("               -o#&&*''''?d:>b\\_")
print("           _o/'`''  '',, dMF9MMMMMHo")
print("        .o&#'        `'MbHMMMMMMMMMMMHo.")
print("      .o'' '         vodM*$&&HMMMMMMMMMM?.")
print("     ,'              $M&ood,~'`(&##MMMMMMH\\")
print("    /               ,MMMMMMM#b?#bobMMMMHMMML")
print("   &              ?MMMMMMMMMMMMMMMMM7MMM$R*Hk")
print("  ?$.            :MMMMMMMMMMMMMMMMMMM/HMMM|`*L")
print(" |               |MMMMMMMMMMMMMMMMMMMMbMH'   T,")
print("$H#:            `*MMMMMMMMMMMMMMMMMMMMb#}'  `?")
print("]MMH#             ''*''''*#MMMMMMMMMMMMM'    -")
print("MMMMMb_                   |MMMMMMMMMMMP'     :")
print("HMMMMMMMHo                 `MMMMMMMMMT       .")
print("?MMMMMMMMP                  9MMMMMMMM}       -")
print("-?MMMMMMM                  |MMMMMMMMM?,d-    '")
print(" :|MMMMMM-                 `MMMMMMMT .M|.   :")
print("  .9MMM[                    &MMMMM*' `'    .")
print("    :9MMk                    `MMM#'        -")
print("     &M}                     `          .-")
print("       `&.                             .")
print("        `~,   .                     ./")
print("           . _                  .-PP")
print("              '`--._,dd###pp='''")